export const ERROR_CODES = Object.freeze({
  TIMER_ACTIVE: 'TIMER_ACTIVE',
  NO_ACTIVE_TIMER: 'NO_ACTIVE_TIMER',
  INVALID_TASK: 'INVALID_TASK',
  INVALID_DATE: 'INVALID_DATE',
  DATA_CORRUPT: 'DATA_CORRUPT',
  IO_ERROR: 'IO_ERROR',
  CONFIG_CORRUPT: 'CONFIG_CORRUPT',
  INVALID_CONFIG: 'INVALID_CONFIG'
});

