/**
 * Códigos de erro estáveis para o ttrack-cli.
 * Seguem o padrão E_NOME_DO_ERRO para facilitar scripting e suporte.
 */
export const ERROR_CODES = Object.freeze({
  // Erros de Ciclo de Vida do Timer
  E_TIMER_ALREADY_RUNNING: 'E_TIMER_ALREADY_RUNNING',
  E_NO_ACTIVE_SESSION: 'E_NO_ACTIVE_SESSION',
  TIMER_ACTIVE: 'E_TIMER_ALREADY_RUNNING',
  NO_ACTIVE_TIMER: 'E_NO_ACTIVE_SESSION',

  // Erros de Validação e Input
  E_INVALID_TASK: 'E_INVALID_TASK',
  E_INVALID_DATE: 'E_INVALID_DATE',
  E_INVALID_PROJECT: 'E_INVALID_PROJECT',
  E_INVALID_CONFIG: 'E_INVALID_CONFIG',
  E_INVALID_INPUT: 'E_INVALID_INPUT',
  E_INVALID_TIME_RANGE: 'E_INVALID_TIME_RANGE',
  INVALID_TASK: 'E_INVALID_TASK',
  INVALID_DATE: 'E_INVALID_DATE',
  INVALID_PROJECT: 'E_INVALID_PROJECT',
  INVALID_CONFIG: 'E_INVALID_CONFIG',
  INVALID_INPUT: 'E_INVALID_INPUT',
  INVALID_TIME_RANGE: 'E_INVALID_TIME_RANGE',

  // Erros de Sessão
  E_SESSION_OVERLAP: 'E_SESSION_OVERLAP',
  SESSION_OVERLAP: 'E_SESSION_OVERLAP',

  // Erros de Projetos e Clientes
  E_PROJECT_NOT_FOUND: 'E_PROJECT_NOT_FOUND',
  E_CLIENT_NOT_FOUND: 'E_CLIENT_NOT_FOUND',
  E_BUDGET_EXCEEDED: 'E_BUDGET_EXCEEDED',
  PROJECT_NOT_FOUND: 'E_PROJECT_NOT_FOUND',
  CLIENT_NOT_FOUND: 'E_CLIENT_NOT_FOUND',
  BUDGET_EXCEEDED: 'E_BUDGET_EXCEEDED',

  // Erros de Exportação
  E_PDF_EXPORT_FAILED: 'E_PDF_EXPORT_FAILED',
  PDF_EXPORT_FAILED: 'E_PDF_EXPORT_FAILED',

  // Erros de Integrações Externas
  E_GITHUB_API_ERROR: 'E_GITHUB_API_ERROR',
  E_WEBHOOK_FAILED: 'E_WEBHOOK_FAILED',
  GITHUB_API_ERROR: 'E_GITHUB_API_ERROR',
  WEBHOOK_FAILED: 'E_WEBHOOK_FAILED',

  // Erros de Plugin
  E_PLUGIN_LOAD_FAILED: 'E_PLUGIN_LOAD_FAILED',
  PLUGIN_LOAD_FAILED: 'E_PLUGIN_LOAD_FAILED',

  // Erros de Infraestrutura
  E_DATA_CORRUPT: 'E_DATA_CORRUPT',
  E_IO_ERROR: 'E_IO_ERROR',
  E_CONFIG_CORRUPT: 'E_CONFIG_CORRUPT',
  DATA_CORRUPT: 'E_DATA_CORRUPT',
  IO_ERROR: 'E_IO_ERROR',
  CONFIG_CORRUPT: 'E_CONFIG_CORRUPT',

  // Erros Genéricos
  E_UNEXPECTED: 'E_UNEXPECTED'
});
